### ISSUE TITLE
Add macOS support

### ISSUE THREAD

**Issue by Alkenso** [pubnub/swift-chat-sdk#9]
Seems SDK is cross-platform and contains only logic, no UI components.

Is it possible to extend the Package to support also macOS?

**Comment by jguz-pubnub** [comment]
Hi @Alkenso, we’re planning to add macOS and tvOS support soon. I’ll let you know when this version becomes available

**Comment by jguz-pubnub** [comment]
Hi @Alkenso, the new `0.9.3-dev` version contains support for macOS and tvOS

**Comment by Alkenso** [comment]
@jguz-pubnub , many thanks for fast update!
